apiVersion: apps/v1
kind: Deployment
metadata:
  name: awsome-app-flux
  labels:
    app: app
  annotations:
    fluxcd.io/automated: "true"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awsome-app-flux
  template:
    metadata:
      labels:
        app: awsome-app-flux
    spec:
      containers:
      - name: awsome-app-flux
        image: 505874605366.dkr.ecr.ap-southeast-2.amazonaws.com/jambaxi-eks:latest
